#!/usr/bin/env python3
"""Regenerate REFERENCE.md by running `live -h` for every verb."""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "REFERENCE.md"
LIVE = [sys.executable, "-m", "live.cli"]


def live_help(*args: str) -> str:
    proc = subprocess.run(
        [*LIVE, *args, "-h"], capture_output=True, text=True, check=True
    )
    return proc.stdout.rstrip()


def discover_verbs(top_help: str) -> list[str]:
    verbs: list[str] = []
    in_block = False
    for line in top_help.splitlines():
        if not in_block:
            if line.lstrip().startswith("<verb>"):
                in_block = True
            continue
        if not line.startswith("    "):
            break
        m = re.match(r"^    (\S+)", line)
        if m:
            verbs.append(m.group(1))
    return verbs


def main() -> None:
    top = live_help()
    parts = ["# `live` — command reference", "", "## `live`", "", "```", top, "```", ""]
    for v in discover_verbs(top):
        parts += [f"## `live {v}`", "", "```", live_help(v), "```", ""]
    parts += ["---", "", "_Autogenerated by `scripts/gen_docs.py`. Do not edit by hand._"]
    OUT.write_text("\n".join(parts).rstrip() + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
