#!/usr/bin/env python3
"""Regenerate REFERENCE.md by running `live -h` for every verb."""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "REFERENCE.md"
LIVE = [sys.executable, "-m", "live.cli"]

# Wide $COLUMNS so argparse keeps usage lines on a single line.
ENV = {**os.environ, "COLUMNS": "200"}


def live_help(*args: str) -> str:
    proc = subprocess.run(
        [*LIVE, *args, "-h"], capture_output=True, text=True, check=True, env=ENV
    )
    return proc.stdout.rstrip()


def live_run(*args: str) -> str:
    proc = subprocess.run(
        [*LIVE, *args], capture_output=True, text=True, check=True, env=ENV
    )
    return proc.stdout.rstrip()


def discover_verbs(top_help: str) -> list[str]:
    verbs: list[str] = []
    in_block = False
    for line in top_help.splitlines():
        if not in_block:
            if line.lstrip().startswith("<verb>"):
                in_block = True
            continue
        if not line.startswith("    "):
            break
        m = re.match(r"^    (\S+)", line)
        if m:
            verbs.append(m.group(1))
    return verbs


def _anchor(verb: str) -> str:
    """GitHub-flavored markdown anchor for a `## \\`live <verb>\\`` heading."""
    return "live-" + re.sub(r"[^a-z0-9]+", "", verb.lower())


def main() -> None:
    top = live_help()
    verbs_ = discover_verbs(top)
    toc = ["- [`live`](#live)"] + [
        f"- [`live {v}`](#{_anchor(v)})" for v in verbs_
    ]
    parts = [
        "# `live` — command reference",
        "",
        *toc,
        "",
        "## `live`",
        "",
        "```",
        top,
        "```",
        "",
    ]
    for v in verbs_:
        parts += [f"## `live {v}`", "", "```", live_help(v), "```", ""]
    parts += [
        "### Agent guide",
        "",
        "```",
        live_run("llms.txt"),
        "```",
        "",
        "---",
        "",
        "_Autogenerated by `scripts/gen_docs.py`. Do not edit by hand._",
    ]
    OUT.write_text("\n".join(parts).rstrip() + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
